# @package _global_
runner:
  profile: hpc_proxy
  queue:
    strategy: fifo
  max_concurrency: ${oc.decode:${oc.env:MAX_CONCURRENCY,1}}
train:
  num_workers: ${oc.decode:${oc.env:NUM_WORKERS,8}}
artifacts:
  level: minimal
